# Chips
stack_size = 20000
big_blind = 100
small_blind = 50

# Bet abstractions, expressed as multiples of the pot size. -1 means "all-in".
# This does not include the call and fold actions. 
bet_abstraction = [
    [1.0, 2.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
]
flop_buckets = 1000    # Max:   1342562
turn_buckets = 1000    # Max:  14403610
river_buckets = 1000   # Max: 125756657

# DCFR
decay = 0.9999

# Filenames
nodes_path = "products/nodes.bin"

# Training
train_iters = 1_000_000
lbr_iters = 200_000
eval_every = 10_000
warm_start = false
player_prune = false
opp_prune = false

# Realtime solving
subgame_solving = true
subgame_iters = 1_000
depth_limit = -1   # -1 means always solve to the end of the game

# Preflop chart
preflop_strategy_path = "products/preflop_strategy.json"
