# Could also get rid of this config file, and instead just hard-code it in config.rs directly. 

# Game
stack_size = 20000
big_blind = 100
small_blind = 50
last_street = "river"

# Bet abstractions, expressed as multiples of the pot size. -1 means "all-in".
# This does not include the call and fold actions. 
bet_abstraction = [
    [1.0, 3.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
]
flop_buckets = 10_000    # Max:   1342562
turn_buckets = 10_000    # Max:  14403610
river_buckets = 10_000   # Max: 125756657

# Filenames
nodes_path = "products/nodes.bin"

# Training
train_iters = 1_000_000
lbr_iters = 2_000_000
eval_every = 10_000
warm_start = false 

# Realtime solving
subgame_solving = true
subgame_iters = 10_000 
depth_limit = -1   # -1 means always solve to the end of the game

# Preflop chart
preflop_strategy_path = "products/preflop_strategy.json"
