# Chips
stack_size = 20000
big_blind = 100
small_blind = 50

# Bet abstractions, expressed as multiples of the pot size. The "all in" action 
# is implicitly included for every street.
bet_abstraction = [
    [1.0, 2.5, 5.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
]
flop_buckets = 100
turn_buckets = 100
river_buckets = 100

# DCFR
alpha = 1.5
beta = 0.0
gamma = 2.0

# Filenames
blueprint_strategy_path = "products/blueprint.bin"
nodes_path = "products/nodes.bin"

# Training
train_iters = 10000000
lbr_iters = 100000
eval_every = 1000000
