# Chips
stack_size = 20000
big_blind = 100
small_blind = 50

# Bet abstractions, expressed as multiples of the pot size. -1 means "all-in".
bet_abstraction = [
    [1.0, 2.5, 5.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
    [0.5, 1.0, -1.0],
]
flop_buckets = 100    # Max: 1342562
turn_buckets = 100    # Max: 14403610
river_buckets = 100   # Max: 125756657

# DCFR
alpha = 1.5
beta = 0.0
gamma = 2.0

# Filenames
nodes_path = "products/nodes.bin"

# Training
train_iters = 10000000
lbr_iters = 10000
eval_every = 100000

# Realtime solving
subgame_solving = false
subgame_iters = 100000

# Preflop chart
preflop_strategy_path = "products/preflop_strategy.json"
